import { Inter } from "next/font/google";
import './styles/globals.css';
import { SocketProvider } from "./context/SocketContext";
import { UserProvider } from "./context/UserContext";
import { RoomProvider } from "./context/RoomContext";  // Ensure this path is correct

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ultimate red-tetris",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
        <SocketProvider>
          <RoomProvider>
          <html lang="en">
            <body className={inter.className}>{children}</body>
          </html>
          </RoomProvider>
        </SocketProvider>
      </UserProvider>
  );
}
